-- Analytical Views for Citi Bike Data
-- Auto-generated by DataFlow-Pro

-- daily_trip_summary

        CREATE OR REPLACE VIEW daily_trip_summary AS
        SELECT
            DATE(start_time) as trip_date,
            COUNT(*) as total_trips,
            AVG(trip_duration) as avg_duration_seconds,
            COUNT(DISTINCT user_id) as unique_users,
            COUNT(DISTINCT start_station_id) as active_start_stations,
            COUNT(DISTINCT end_station_id) as active_end_stations
        FROM trips
        GROUP BY DATE(start_time)
        ORDER BY trip_date;
    

-- station_popularity

        CREATE OR REPLACE VIEW station_popularity AS
        SELECT
            bs.station_id,
            bs.station_name,
            bs.latitude,
            bs.longitude,
            COUNT(DISTINCT t1.trip_id) as trips_started,
            COUNT(DISTINCT t2.trip_id) as trips_ended,
            COUNT(DISTINCT t1.trip_id) + COUNT(DISTINCT t2.trip_id) as total_activity
        FROM bike_stations bs
        LEFT JOIN trips t1 ON bs.station_id = t1.start_station_id
        LEFT JOIN trips t2 ON bs.station_id = t2.end_station_id
        GROUP BY bs.station_id, bs.station_name, bs.latitude, bs.longitude
        ORDER BY total_activity DESC;
    

-- weather_impact_on_trips

        CREATE OR REPLACE VIEW weather_impact_on_trips AS
        SELECT
            DATE(t.start_time) as trip_date,
            COUNT(t.trip_id) as total_trips,
            AVG(t.trip_duration) as avg_duration,
            wd.tmax as max_temp_f,
            wd.tmin as min_temp_f,
            wd.prcp as precipitation_inches,
            wd.snow as snow_inches,
            wd.awnd as avg_wind_speed
        FROM trips t
        INNER JOIN weather_dates wd ON DATE(t.start_time) = wd.date
        GROUP BY DATE(t.start_time), wd.tmax, wd.tmin, wd.prcp, wd.snow, wd.awnd
        ORDER BY trip_date;
    

-- user_demographics

        CREATE OR REPLACE VIEW user_demographics AS
        SELECT
            u.user_type,
            u.gender,
            2016 - u.birth_year as age_in_2016,
            COUNT(DISTINCT t.trip_id) as total_trips,
            AVG(t.trip_duration) as avg_trip_duration,
            MIN(t.start_time) as first_trip,
            MAX(t.start_time) as last_trip
        FROM users u
        LEFT JOIN trips t ON u.user_id = t.user_id
        GROUP BY u.user_type, u.gender, u.birth_year
        ORDER BY total_trips DESC;
    

-- monthly_trends

        CREATE OR REPLACE VIEW monthly_trends AS
        SELECT
            DATE_TRUNC('month', start_time) as month,
            COUNT(*) as total_trips,
            AVG(trip_duration) as avg_duration,
            COUNT(DISTINCT user_id) as unique_users,
            COUNT(CASE WHEN user_type = 'Subscriber' THEN 1 END) as subscriber_trips,
            COUNT(CASE WHEN user_type = 'Customer' THEN 1 END) as customer_trips
        FROM trips t
        JOIN users u ON t.user_id = u.user_id
        GROUP BY DATE_TRUNC('month', start_time)
        ORDER BY month;
    

