-- Citi Bike Star Schema DDL
-- Auto-generated by DataFlow-Pro

-- Schema DDL for citibike_star_schema
-- Generated for POSTGRESQL
-- Schema Pattern: FLAT
-- Total tables: 5
-- Generated on: 2025-10-29 22:43:06

CREATE TABLE trips (
    User ID SMALLINT NOT NULL,
    Start Station ID SMALLINT NOT NULL,
    End Station ID SMALLINT NOT NULL,
    Trip Duration INTEGER NOT NULL,
    Start Time TEXT NOT NULL,
    Stop Time TEXT NOT NULL,
    Bike ID SMALLINT NOT NULL,
    PRIMARY KEY (Start Time, Stop Time)
);

CREATE TABLE users (
    User ID SMALLINT NOT NULL,
    User Type TEXT NOT NULL,
    Birth Year REAL NOT NULL,
    Gender SMALLINT NOT NULL,
    PRIMARY KEY (User ID, Birth Year)
);

CREATE TABLE bike_stations (
    Station ID SMALLINT NOT NULL,
    Station Name TEXT NOT NULL,
    Latitude REAL NOT NULL,
    Longitude REAL NOT NULL,
    PRIMARY KEY (Station ID, Station Name)
);

CREATE TABLE weather_stations (
    Weather Station ID SMALLINT NOT NULL,
    Station TEXT NOT NULL,
    Name TEXT NOT NULL,
    PRIMARY KEY (Weather Station ID, Station)
);

CREATE TABLE weather_dates (
    Weather Station ID SMALLINT NOT NULL,
    DATE DATE NOT NULL,
    AWND REAL NOT NULL,
    PGTM TEXT,
    PRCP REAL NOT NULL,
    SNOW REAL NOT NULL,
    SNWD REAL NOT NULL,
    TAVG SMALLINT NOT NULL,
    TMAX SMALLINT NOT NULL,
    TMIN SMALLINT NOT NULL,
    TSUN TEXT,
    WDF2 SMALLINT NOT NULL,
    WDF5 REAL NOT NULL,
    WSF2 REAL NOT NULL,
    WSF5 REAL NOT NULL,
    PRIMARY KEY (DATE, TMAX)
);

-- Foreign Key Constraints

ALTER TABLE trips ADD CONSTRAINT fk_trips_User ID FOREIGN KEY (User ID) REFERENCES users(User ID);
ALTER TABLE trips ADD CONSTRAINT fk_trips_Start Station ID FOREIGN KEY (Start Station ID) REFERENCES bike_stations(Station ID);
ALTER TABLE trips ADD CONSTRAINT fk_trips_End Station ID FOREIGN KEY (End Station ID) REFERENCES bike_stations(Station ID);
ALTER TABLE weather_dates ADD CONSTRAINT fk_weather_dates_Weather Station ID FOREIGN KEY (Weather Station ID) REFERENCES weather_stations(Weather Station ID);

-- Pattern-Optimized Indexes

CREATE UNIQUE INDEX pk_table ON trips(Start Time, Stop Time);
CREATE INDEX idx_table_User ID ON trips(User ID);
CREATE INDEX idx_table_Start Station ID ON trips(Start Station ID);
CREATE INDEX idx_table_End Station ID ON trips(End Station ID);
CREATE INDEX idx_table_Bike ID ON trips(Bike ID);
CREATE UNIQUE INDEX pk_table ON users(User ID, Birth Year);
CREATE UNIQUE INDEX pk_table ON bike_stations(Station ID, Station Name);
CREATE INDEX idx_table_Latitude ON bike_stations(Latitude);
CREATE INDEX idx_table_Longitude ON bike_stations(Longitude);
CREATE UNIQUE INDEX pk_table ON weather_stations(Weather Station ID, Station);
CREATE UNIQUE INDEX pk_table ON weather_dates(DATE, TMAX);
CREATE INDEX idx_table_Weather Station ID ON weather_dates(Weather Station ID);
